[package]
name = "critic-format"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.37.2", features = ["serialize"] }
serde = { version = "1.0.217", features = ["derive"] }
