name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint check
      run: cargo fmt --check
    - name: Build release
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose

