name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests - no features
      run: cargo test --verbose --no-default-features
    - name: Run tests - alloc
      run: cargo test --verbose --no-default-features --features alloc
    - name: Run tests - std
      run: cargo test --verbose
    - name: Run tests - all features
      run: cargo test --verbose --all-features

